# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_hello']

# Cell
def print_hello(to):
    "Print hello to the user"
    return f"Hello, {to}!"